import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export default new Router({
  mode:'history',
  routes: [
    {
      path:'/login',
      component:()=>import('@/pages/login')
    },
    {
      path:'/index',
      component:()=>import('@/pages/index'),
      children:[
        {
          path:'/home',
          component:()=>import('@/views/home')
        },
        {
          path:'/menu',
          component:()=>import('@/views/menu/index.vue'),
          meta:{
            name:'菜单列表'
          }
        },
        {
          path:'/role',
          component:()=>import('@/views/role/index.vue'),
          meta:{
            name:'角色列表'
          }
        },
        {
          path:'/user',
          component:()=>import('@/views/user/index.vue'),
          meta:{
            name:'管理员列表'
          }
        },
        {
          path:'/sort',
          component:()=>import('@/views/sort/index.vue'),
          meta:{
            name:'商品分类列表'
          }
        },       
         {
          path:'/specs',
          component:()=>import('@/views/specs/index.vue'),
          meta:{
            name:'商品规格列表'
          }
        },
        {
          path:'/goods',
          component:()=>import('@/views/goods/index.vue'),
          meta:{
            name:'商品管理'
          }
        },
        {
          path:'/member',
          component:()=>import('@/views/member/index.vue'),
          meta:{
            name:'会员管理'
          }
        },
        {
          path:'/banner',
          component:()=>import('@/views/banner/index.vue'),
          meta:{
            name:'轮播图管理'
          }
        },
        {
          path:'/seck',
          component:()=>import('@/views/seck/index.vue'),
          meta:{
            name:'限时秒杀'
          }
        },
        {
          path:'',
          redirect:'/home'
        }
      ]
    },
    {
      path:'*',
      redirect:'/index'
    }
  ]
})
